        # version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orderme-net

  backend:
    build: ./backend
    env_file: .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - orderme-net

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - orderme-net

networks:
  orderme-net:
    driver: bridge

volumes:
  postgres_data: